# TODO (revisit): add a sourceImage field to RecipeModel to retain the original
# image used during AI extraction. Useful during edit for cross-referencing
# handwritten notes the extractor may have missed. See matching TODOs in
# save_recipe_api.py (storage on /extract) and recipe_form_styled.html (UI).
# Decide: single field vs. list (re-extractions / multi-page sources), URL vs.
# stored path, and back-fill strategy for existing records.

from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Union, Literal
from datetime import datetime
import os

class AggregateRating(BaseModel):
    type: str = Field(default="AggregateRating", alias="@type")
    ratingValue: float
    reviewCount: int

class NutritionInfo(BaseModel):
    calories: Optional[str] = ""
    fatContent: Optional[str] = ""
    carbohydrateContent: Optional[str] = ""
    proteinContent: Optional[str] = ""

class HowToStep(BaseModel):
    type: str = Field(default="HowToStep", alias="@type")
    position: Optional[int] = None
    name: Optional[str] = None
    text: str
    image: Optional[str] = None
    imageCredit: Optional[str] = None

class Tool(BaseModel):
    type: str = Field(default="HowToTool", alias="@type")
    name: str

class VideoObject(BaseModel):
    type: str = Field(default="VideoObject", alias="@type")
    name: str
    contentUrl: str
    thumbnailUrl: Optional[str] = ""
    uploadDate: Optional[str] = ""
    description: Optional[str] = ""

class Author(BaseModel):
    type: str = Field(default="Person", alias="@type")
    name: Optional[str] = ""
    image: Optional[str] = None

class Provenance(BaseModel):
    ethnicity: Optional[str] = ""
    originRegion: Optional[str] = ""
    firstDocumented: Optional[str] = None
    traditionalContext: Optional[str] = ""
    notableVariations: Optional[List[str]] = []
    relatedDishes: Optional[List[str]] = []
    sources: Optional[List[dict]] = []

class AccessControl(BaseModel):
    visibility: Optional[str] = ""
    sharedWith: Optional[List[str]] = []

class SourceInfo(BaseModel):
    type: Optional[str] = ""
    origin: Optional[str] = ""
    originalUrl: Optional[str] = ""
    affiliateUrl: Optional[str] = ""

# Pipeline-side metadata. Defaults are empty so interactive saves don't have to
# populate them; batch stages fill them in over time.
class ScoringMetadata(BaseModel):
    pageAuthority: float = 0.0
    domainAuthority: float = 0.0
    ouScore: float = 0.0
    rootDomain: str = ""
    rawTitle: str = ""
    iconUrl: str = ""
    recipeScore: int = 0
    recipeScoreThreshold: int = 0

class ClassificationMetadata(BaseModel):
    confidence: int = 0
    reasoning: str = ""
    hierarchyPath: str = ""
    story: str = ""
    # Cookbook chapter (flat enum, one of CHAPTERS from
    # extract/chapter_classifier.py). Populated at extract time by the
    # keyword-shortcut + LLM-fallback classifier. Editable on the form;
    # user override persists.
    chapter: str = ""


# Editorial commentary on a specific recipe (not the dish — see story for
# dish history). Generated by the same enrich LLM call. Three free-form
# markdown strings so the LLM can format with paragraphs/bullets as it
# sees fit; the form renders them in auto-grow textareas.
class EditorialMetadata(BaseModel):
    # Editorial opinion on THIS recipe: technique, ingredient ratios, what
    # makes it work or wobble, who'd enjoy it.
    opinion: str = ""
    # Prose interpretation of the PA/DA/OU scores: how the page authority
    # relates to the domain authority, whether the recipe punches above or
    # below its domain's weight.
    scoreCommentary: str = ""
    # Markdown bullets like "- **Olive oil**: raw in this recipe, so
    # quality dominates. Look for cold-pressed Ligurian or Tuscan...".
    # Stored as a single string; the LLM is free to bullet or paragraph.
    # No affiliate links yet — placeholders for product names only.
    sourcingNotes: str = ""

class StatusField(BaseModel):
    value: Literal["accepted", "rejected"]
    reason: Optional[str] = None
    timestamp: Optional[str] = None

class RecipeModel(BaseModel):
    model_config = {"populate_by_name": True, "extra": "allow"}

    context: Optional[str] = Field(default="https://schema.org", alias="@context")
    type: Optional[str] = Field(default="Recipe", alias="@type")
    id: Optional[str] = ""
    name: Optional[str] = ""
    description: Optional[str] = ""
    image: Optional[List[str]] = []
    author: Optional[Author] = None
    datePublished: Optional[str] = ""
    dateModified: Optional[str] = ""
    recipeYield: Optional[str] = ""
    prepTime: Optional[str] = ""
    cookTime: Optional[str] = ""
    totalTime: Optional[str] = ""
    recipeCategory: Optional[str] = ""
    recipeCuisine: Optional[str] = ""
    keywords: Optional[List[str]] = []
    aggregateRating: Optional[AggregateRating] = None
    nutrition: Optional[NutritionInfo] = None
    recipeIngredient: Optional[List[str]] = []
    recipeInstructions: Optional[List[HowToStep]] = []
    notes: Optional[str] = ""
    tags: Optional[List[str]] = []
    video: Optional[Union[VideoObject, str]] = None
    servingSuggestions: Optional[str] = ""
    cookingMethod: Optional[str] = ""
    equipment: Optional[List[Tool]] = []
    suitableForDiet: Optional[List[str]] = []
    provenance: Optional[Provenance] = None
    imageSource: Optional[str] = ""
    inputImage: Optional[str] = None
    imported_from: Optional[str] = Field(default="", alias="_imported_from")
    editor_version: Optional[str] = Field(default="", alias="_editor_version")
    access: Optional[AccessControl] = Field(default=None, alias="_access")
    source: Optional[SourceInfo] = Field(default=None, alias="_source")
    scoring: Optional[ScoringMetadata] = Field(default=None, alias="_scoring")
    classification: Optional[ClassificationMetadata] = None
    editorial: Optional[EditorialMetadata] = None
    current_status: Optional[StatusField] = None
    # Owner discriminator. 0 = sys-admin / batch-curated master collection
    # (lives in master_recipes table); any other value = personal collection
    # (recipes table). Pydantic must know about this field explicitly so it
    # survives `model_dump(by_alias=True, exclude_none=True)` in
    # sanitize_recipe_data — `extra="allow"` accepts unknown fields on
    # construction but drops them on dump.
    user_id: Optional[int] = None

    @field_validator('servingSuggestions', mode='before')
    @classmethod
    def convert_serving_suggestions(cls, v):
        if isinstance(v, list):
            return ", ".join(str(item) for item in v if item)
        return v

    def is_nullish(self, value):
        return value in [None, "", [], {}, "null", "None"] or (
            isinstance(value, list) and all(self.is_nullish(v) for v in value)
        )

    def file_exists(self, path):
        try:
            return os.path.exists(path) and os.path.isfile(path)
        except:
            return False

    def needs_image_generation(self) -> bool:
        has_valid_image_file = any(
            isinstance(img, str) and not self.is_nullish(img) and self.file_exists(img)
            for img in self.image or []
        )
        return (
            not has_valid_image_file and
            self.is_nullish(self.imageSource)
        )

    def prefers_dish_image(self) -> bool:
        return (
            not self.is_nullish(self.name) and
            not self.is_nullish(self.recipeIngredient) and
            any(
                step and hasattr(step, "text") and isinstance(step.text, str) and step.text.strip()
                for step in self.recipeInstructions or []
            )
        )

    def generate_prompt(self) -> str:
        ingredient_sample = ", ".join(self.recipeIngredient[:3]) if self.recipeIngredient else ""

        if self.prefers_dish_image():
            base = f"A plated, fully prepared version of '{self.name}',"

            # Add equipment context for proper shape/presentation
            if self.equipment:
                equipment_names = []
                for item in self.equipment:
                    if hasattr(item, 'name') and item.name:
                        equipment_names.append(item.name.lower())
                    elif isinstance(item, dict) and 'name' in item:
                        equipment_names.append(item['name'].lower())
                    elif isinstance(item, str):
                        equipment_names.append(item.lower())

                if equipment_names:
                    equipment_text = ", ".join(equipment_names)
                    if any(word in equipment_text for word in ['pie', 'round', 'circular']):
                        base += f" in a round {equipment_text},"
                    elif any(word in equipment_text for word in ['baking dish', 'casserole', 'pan']):
                        base += f" in a {equipment_text},"
                    else:
                        base += f" using {equipment_text},"

            # Add cooking method context
            if self.cookingMethod and not self.is_nullish(self.cookingMethod):
                method = self.cookingMethod.lower()
                if 'baking' in method or 'baked' in method:
                    base += f" golden and bubbling from baking,"
                elif 'frying' in method or 'fried' in method:
                    base += f" with crispy, golden edges from frying,"
                elif 'grilling' in method or 'grilled' in method:
                    base += f" with grill marks and charred edges,"

            # Extract visual details from instructions
            visual_details = self._extract_visual_details_from_instructions()
            if visual_details:
                base += f" {visual_details},"

            if self.servingSuggestions and not self.is_nullish(self.servingSuggestions):
                base += f" served with {self.servingSuggestions.strip().rstrip('.')},"
            if self.recipeCuisine and not self.is_nullish(self.recipeCuisine):
                base += f" in a {self.recipeCuisine} style,"
            if ingredient_sample:
                base += f" made with ingredients like {ingredient_sample},"
            if self.description and not self.is_nullish(self.description):
                base += f" {self.description.strip().rstrip('.')}"
            return base + " — cookbook photo quality, natural lighting, minimal background."
        else:
            return f"Stylized flat-lay image of the key ingredients for '{self.name}': " + \
                ", ".join(self.recipeIngredient or []) + \
                ". Clean composition, soft shadows, cookbook illustration style."

    def _extract_visual_details_from_instructions(self) -> str:
        """Extract visual presentation details from recipe instructions"""
        if not self.recipeInstructions:
            return ""

        visual_keywords = {
            'garnish': ['garnish', 'top with', 'sprinkle', 'arrange', 'decorate'],
            'texture': ['golden', 'brown', 'crispy', 'bubbly', 'bubbling', 'melted', 'caramelized'],
            'appearance': ['fancy', 'elegant', 'beautiful', 'attractive', 'colorful'],
            'placement': ['center', 'around', 'on top', 'between', 'in the middle'],
            'final_touch': ['finish', 'final', 'serve', 'present', 'display']
        }

        visual_details = []

        for step in self.recipeInstructions:
            if not step or not hasattr(step, 'text') or not step.text:
                continue

            step_text = step.text.lower()

            # Look for garnish and topping details
            if any(keyword in step_text for keyword in visual_keywords['garnish']):
                # Extract specific garnish items
                if 'olive' in step_text:
                    visual_details.append("topped with olives")
                if 'asparagus' in step_text and 'tip' in step_text:
                    visual_details.append("garnished with asparagus tips")
                if 'cheese' in step_text and any(word in step_text for word in ['slice', 'grated', 'melted']):
                    visual_details.append("with melted cheese on top")
                if 'herb' in step_text or 'parsley' in step_text or 'cilantro' in step_text:
                    visual_details.append("garnished with fresh herbs")

            # Look for texture/appearance cues
            if any(keyword in step_text for keyword in visual_keywords['texture']):
                if 'golden' in step_text and 'brown' in step_text:
                    visual_details.append("golden brown and crispy")
                elif 'bubbly' in step_text or 'bubbling' in step_text:
                    visual_details.append("bubbling hot")
                elif 'golden' in step_text:
                    visual_details.append("golden colored")
                elif 'caramelized' in step_text:
                    visual_details.append("with caramelized edges")

            # Look for specific plating/presentation instructions
            if 'fancy' in step_text and 'top' in step_text:
                # Extract the fancy topping description
                fancy_parts = step_text.split('fancy top')[1] if 'fancy top' in step_text else ""
                if fancy_parts and len(fancy_parts) < 100:  # Keep it reasonable length
                    visual_details.append(f"elegantly presented{fancy_parts.split('.')[0]}")

        # Remove duplicates and join
        unique_details = list(dict.fromkeys(visual_details))  # Preserves order
        return ", ".join(unique_details[:3])  # Limit to 3 most important details
