"""Dish identity card — structured fact extraction + dish inference.

This is the canonical structured representation of a recipe's dish
identity. Generated by a single Haiku call at save time using
tool_use with an ordered schema that forces the LLM to commit to
structural facts (ingredient roles, cuisine, technique) BEFORE
concluding the canonical dish family. Chain-of-thought via schema —
the LLM can't make the dish judgment until it's named the facts that
support it.

Why this exists (vs the older `dish_signal` prose blob):

The earlier `extract/dish_signal.py` asked Haiku to produce a one-line
prose description in a single judgment call. Whatever surface detail
caught the LLM's attention first (an exotic ingredient, a cuisine
label, a creative recipe title) anchored the answer. The Salted Tahini
Chocolate Chip Cookies case landed as "Israeli butter cookie" — Haiku
weighted the differentiating tokens (tahini, Israeli) over the
structural facts (butter+sugar+flour+chocolate chips, Cookies & Bars
chapter). Cohort matching then missed.

Identity card inverts the pipeline: facts first, conclusion derived.
The same Haiku call produces both — but the tool_use schema lists the
fact fields FIRST in property order, so the LLM emits them first and
commits to them before getting to `likelyDish`. The conclusion is
forced to reason from the structured facts the model has just
recorded.

Storage shape (top-level `_identity` on recipes):

    {
      "ingredientRoles": [
        {"text": "ground beef", "role": "main_protein"},
        {"text": "spaghetti", "role": "starch"},
        ...
      ],
      "cuisine": "Italian-American",
      "ethnicity": "Italian-American",
      "technique": "meatballs browned then simmered in sauce; pasta cooked separately",
      "servingForm": "pasta topped with meatballs and sauce",
      "likelyDish": "Spaghetti and Meatballs",
      "primaryIngredients": ["ground beef", "spaghetti", "tomato sauce", "breadcrumbs"]
    }

`primaryIngredients` is derived from `ingredientRoles` by filtering to
PRIMARY_ROLES — same selection rule on every read, no second LLM call.

Used by:
  - `compose_recipe_text` in input/pipeline/embeddings.py: lifts
    likelyDish + cuisine + primary + technique as the embedding source.
  - Future: search facets, ingredient-role-keyed ecommerce, structured
    UI displays, cross-recipe analytics.
"""
from __future__ import annotations

import hashlib
from typing import Optional

import anthropic


_anthropic_client = anthropic.Anthropic()


# 14 structural roles spanning the dish surface area. Order in this
# list is presentational only — what matters is that every ingredient
# gets exactly one tag, and that PRIMARY_ROLES below defines which
# ones count as dish-defining vs supporting.
INGREDIENT_ROLES = [
    "main_protein",        # the centerpiece protein: chicken, beef, fish, tofu, eggs (when main)
    "primary_vegetable",   # the dish-defining vegetable: asparagus in au gratin, spinach in spanakopita
    "starch",              # pasta, rice, potatoes, bread used structurally
    "pastry",              # phyllo, pie crust, puff pastry
    "dairy",               # milk, cream, cheese, yogurt, butter when DAIRY-SOURCED
    "sauce_base",          # tomato sauce, stock, wine, broth (structural, not just liquid)
    "filling",             # what's inside a wrapped/stuffed dish — distinct from main_protein
    "seasoning",           # salt, pepper, herbs, spices in supporting role
    "fat",                 # oil, lard, schmaltz, neutral butter
    "liquid",              # water, broth used functionally (not as sauce_base)
    "garnish",             # fresh herbs, citrus zest, finishing items
    "binder",              # eggs, breadcrumbs, flour used to bind (not as main)
    "sweetener",           # sugar, honey, maple syrup
    "leavening",           # yeast, baking powder, baking soda
]


# Roles whose ingredients qualify as "primary" — the dish-identity-
# bearing components. Derived from INGREDIENT_ROLES selection at every
# read; never re-prompted, never re-derived.
PRIMARY_ROLES = {
    "main_protein",
    "primary_vegetable",
    "starch",
    "pastry",
    "sauce_base",
    "filling",
}


# Tool schema. Property ORDER matters: Anthropic's tool_use emits keys
# in declared order, so listing the fact fields first forces the LLM
# to commit to them before reaching `likelyDish`. The conclusion has
# to reason from the facts it just recorded.
IDENTITY_TOOL = {
    "name": "submit_dish_identity",
    "description": (
        "Record the dish identity card for a recipe. Fill in the "
        "structural facts FIRST (ingredient roles, cuisine, ethnicity, "
        "technique, serving form), THEN derive the canonical dish "
        "family name from those facts."
    ),
    "input_schema": {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "ingredientRoles",
            "cuisine",
            "ethnicity",
            "technique",
            "servingForm",
            "likelyDish",
        ],
        "properties": {
            # FACTS — must be committed to first.
            "ingredientRoles": {
                "type": "array",
                "description": (
                    "One entry per ingredient in the recipe (in the order "
                    "the recipe lists them), with each ingredient tagged "
                    "with exactly one structural role. `text` should be "
                    "the ingredient noun (no measurements or qualifiers — "
                    "use 'tahini' not '½ cup tahini, well stirred')."
                ),
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["text", "role"],
                    "properties": {
                        "text": {
                            "type": "string",
                            "description": (
                                "The ingredient noun, stripped of "
                                "measurement and qualifier text."
                            ),
                        },
                        "role": {
                            "type": "string",
                            "enum": INGREDIENT_ROLES,
                            "description": (
                                "The structural role this ingredient "
                                "plays in this specific dish. Same "
                                "ingredient can be different roles in "
                                "different dishes (butter is fat in "
                                "cookies, dairy in a butter sauce)."
                            ),
                        },
                    },
                },
            },
            "cuisine": {
                "type": "string",
                "description": (
                    "Broad culinary tradition the dish belongs to: "
                    "Italian, French, Greek, American, Japanese, Mexican, "
                    "etc. Use 'Italian-American' / 'Chinese-American' "
                    "for diaspora cuisines. Empty string when genuinely "
                    "unidentifiable."
                ),
            },
            "ethnicity": {
                "type": "string",
                "description": (
                    "More specific cultural/regional origin: Sicilian, "
                    "Provençal, Yucatecan, Sephardic, etc. Often the "
                    "same as cuisine for non-regional dishes. Empty "
                    "string when not applicable."
                ),
            },
            "technique": {
                "type": "string",
                "description": (
                    "One-sentence description of the core cooking "
                    "technique that defines this dish. Examples: "
                    "'meatballs browned then simmered in sauce, pasta "
                    "cooked separately', 'pasta tossed with raw egg "
                    "sauce and rendered pancetta', 'layered phyllo "
                    "baked over spinach-feta filling'."
                ),
            },
            "servingForm": {
                "type": "string",
                "description": (
                    "How the dish is presented at the table. Examples: "
                    "'pasta topped with sauce', 'baked casserole sliced "
                    "into squares', 'rolled and sliced like sushi'."
                ),
            },
            # CONCLUSION — MUST come after the facts above. The LLM
            # has now committed to the structural picture and must
            # derive the canonical dish from what it just recorded.
            "likelyDish": {
                "type": "string",
                "description": (
                    "GIVEN the ingredient roles, cuisine, technique, "
                    "and serving form above, name the closest canonical "
                    "traditional dish family — even when this recipe is "
                    "a variant. Examples of correct reasoning: a recipe "
                    "with main_protein=ground beef + starch=spaghetti + "
                    "sauce_base=tomato + Italian-American → 'Spaghetti "
                    "and Meatballs'. A recipe with starch=none + "
                    "primary=butter+sugar+flour+chocolate chips + "
                    "chapter=Cookies & Bars, even with tahini in the "
                    "ingredient list, → 'Chocolate Chip Cookies' (as a "
                    "tahini variant). Lead with the canonical family "
                    "name; do NOT lead with the differentiating "
                    "ingredient. When genuinely no canonical family "
                    "fits, use descriptive structural language."
                ),
            },
        },
    },
}


_SYSTEM_PROMPT = (
    "You generate structured dish identity cards by extracting facts "
    "FIRST and then concluding the canonical dish family.\n\n"
    "WORKFLOW (the tool schema enforces this order — follow it):\n\n"
    "1. ingredientRoles: tag each ingredient with one structural role. "
    "Use the ingredient NOUN only (no measurements or qualifiers). "
    "Same ingredient gets different roles in different dishes — butter "
    "is `fat` in cookies but `dairy` in a butter sauce; spinach is "
    "`primary_vegetable` in a salad but `filling` in spanakopita.\n\n"
    "2. cuisine: broad culinary tradition (Italian, French, Greek, "
    "American, etc.). Hyphenate for diaspora cuisines (Italian-"
    "American).\n\n"
    "3. ethnicity: more specific regional origin if applicable; "
    "otherwise echo cuisine.\n\n"
    "4. technique: one sentence on the defining cooking technique.\n\n"
    "5. servingForm: how the dish lands at the table.\n\n"
    "6. likelyDish: GIVEN your facts above, what canonical traditional "
    "dish family is this? CRITICAL: lead with the CANONICAL FAMILY "
    "NAME, even if the recipe is a variant. A salted-tahini chocolate "
    "chip cookie is `Chocolate Chip Cookies` (with tahini as a variant "
    "differentiator), NOT `Israeli butter cookie`. A Pastitsio variant "
    "with penne instead of macaroni is still `Pastitsio`. Match to the "
    "closest established cookbook chapter heading, not the most "
    "creative description.\n\n"
    "Output ONLY through the submit_dish_identity tool — no narration, "
    "no preamble."
)


IDENTITY_PROMPT_VERSION = hashlib.sha256(
    _SYSTEM_PROMPT.encode("utf-8")
).hexdigest()[:12]


_MODEL = "claude-haiku-4-5"
_MAX_TOKENS = 1200
_TEMPERATURE = 0.2


def _build_recipe_user_prompt(recipe: dict) -> str:
    """Compose the user message for a recipe's identity card. We give
    Haiku the same minimal slice that dish_signal had: name + cuisine
    hints + chapter + recipe description + ingredients. NO measurement
    stripping happens here — the LLM is instructed to do that as part
    of populating ingredientRoles.text."""
    name = (recipe.get("name") or "").strip()
    cls = recipe.get("classification") or {}
    prov = recipe.get("provenance") or {}
    cuisine = (recipe.get("recipeCuisine") or "").strip()
    chapter = (cls.get("chapter") or "").strip()
    ethnicity = (prov.get("ethnicity") or "").strip()
    description = (recipe.get("description") or "").strip()

    ings_raw = recipe.get("recipeIngredient") or []
    ings: list[str] = []
    for ing in ings_raw[:25]:  # 25 is plenty — most recipes have 8-15
        if isinstance(ing, str):
            ings.append(ing.strip())
        elif isinstance(ing, dict):
            ings.append(str(ing.get("text") or ing.get("name") or "").strip())
    ings = [i for i in ings if i]

    lines = [f"Recipe name: {name}"]
    if cuisine:
        lines.append(f"Site-declared cuisine hint: {cuisine}")
    if ethnicity:
        lines.append(f"Site-declared ethnicity hint: {ethnicity}")
    if chapter:
        lines.append(f"Cookbook chapter: {chapter}")
    if description:
        lines.append(f"Recipe description: {description[:600]}")
    if ings:
        lines.append("Ingredients (as written by the source):")
        for ing in ings:
            lines.append(f"  - {ing}")
    return "\n".join(lines)


def _build_dish_user_prompt(dish_row: dict) -> str:
    """Compose the user message for a dish's identity card. Dishes
    have NO ingredient list — Haiku invents the prototypical
    ingredient roster for the canonical version of the dish based on
    name + queries + curator-supplied description (when present)."""
    name = (dish_row.get("name") or "").strip()
    description = (dish_row.get("description") or "").strip()
    queries = dish_row.get("queries") or []

    lines = [f"Dish name: {name}"]
    if queries:
        clean = [str(q).strip() for q in queries
                 if str(q).strip() and str(q).strip().lower() != name.lower()]
        if clean:
            lines.append("Alternate names / query variants: " + ", ".join(clean))
    if description:
        lines.append(f"Curator description: {description}")
    lines.append(
        "Provide the canonical (most traditional) version's identity card. "
        "For ingredientRoles, list the prototypical ingredients of the "
        "classic version with their structural roles."
    )
    return "\n".join(lines)


def _call_identity_tool(user_prompt: str, *,
                         usage_log: Optional[list] = None,
                         operation: str) -> Optional[dict]:
    """Shared LLM call shape. Returns the validated tool input dict, or
    None on failure. Never raises — caller falls back to its prior
    composition path."""
    try:
        response = _anthropic_client.messages.create(
            model=_MODEL,
            max_tokens=_MAX_TOKENS,
            temperature=_TEMPERATURE,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
            tools=[IDENTITY_TOOL],
            tool_choice={"type": "tool", "name": "submit_dish_identity"},
        )
    except Exception as e:
        print(f"[IDENTITY] LLM call failed: {type(e).__name__}: {e}")
        return None

    if usage_log is not None:
        try:
            from input.pipeline.token_journal import build_usage_entry
            usage_log.append(build_usage_entry(operation, _MODEL, response))
        except Exception:
            pass

    tool_input = next(
        (b.input for b in response.content
         if getattr(b, "type", "") == "tool_use"
         and getattr(b, "name", "") == "submit_dish_identity"),
        None,
    )
    if not isinstance(tool_input, dict):
        return None
    return tool_input


def _derive_primary_ingredients(roles: list) -> list[str]:
    """Filter ingredientRoles to PRIMARY_ROLES and return the texts in
    original order. Used at read time; never re-prompted."""
    out: list[str] = []
    for entry in roles or []:
        if not isinstance(entry, dict):
            continue
        if (entry.get("role") or "") in PRIMARY_ROLES:
            text = (entry.get("text") or "").strip()
            if text:
                out.append(text)
    return out


def _attach_primary(card: dict) -> dict:
    """Stamp primaryIngredients onto the card from its ingredientRoles.
    The card returned by the LLM has only the fact fields + likelyDish;
    primaryIngredients is a derived view we always compute the same way."""
    card["primaryIngredients"] = _derive_primary_ingredients(
        card.get("ingredientRoles") or []
    )
    return card


def generate_identity_card_for_recipe(recipe: dict, *,
                                       usage_log: Optional[list] = None
                                       ) -> Optional[dict]:
    """Generate the identity card for a recipe. Returns the card dict
    (with `primaryIngredients` derived) or None on failure. Caller
    stamps the result on `recipe["_identity"]`."""
    if not (recipe.get("name") or "").strip():
        return None
    user_prompt = _build_recipe_user_prompt(recipe)
    card = _call_identity_tool(
        user_prompt, usage_log=usage_log,
        operation="identity_card_recipe",
    )
    if card is None:
        return None
    return _attach_primary(card)


def generate_identity_card_for_dish(dish_row: dict, *,
                                     usage_log: Optional[list] = None
                                     ) -> Optional[dict]:
    """Generate the identity card for a dish entry. Dishes don't have
    a real ingredient list; the LLM invents the canonical prototype's
    roster. Caller stamps the result on the dishes row (column TBD —
    likely a JSON `identity_card` column added in the dish-side spec
    follow-up)."""
    if not (dish_row.get("name") or "").strip():
        return None
    user_prompt = _build_dish_user_prompt(dish_row)
    card = _call_identity_tool(
        user_prompt, usage_log=usage_log,
        operation="identity_card_dish",
    )
    if card is None:
        return None
    return _attach_primary(card)
